export const siteConfig = {
  name: "Baris Atala | AtalaDev",
  authorName: "Barış Atala",
  username: "barisatala",
  description: "Founder of AtalaDev | Freelance Full Stack Developer,",
  url: "https://ataladev.com",
  links: {
    twitter: "https://x.com/namanbarkiya",
    github: "https://github.com/AtalaBaris",
    templateRepo: "https://github.com/namanbarkiya/minimal-next-portfolio",
  },

  keywords: [
    "Barış Atala",
    "AtalaDev",
    "Software Engineer",
    "Full Stack Developer",
    "Freelance Developer",
    "Web Development",
    "modern web development",
    "Mobile Development",
    "Machine Learning",
    "Python Developer",
    "React Developer",
    "Next.js Developer",
    "TypeScript",
    "JavaScript",
    "AI Startups",
    "Software Development",
    "Web Developer",
    "Backend Developer",
    "Frontend Developer",
    "Tech Portfolio",
  ],
};
